apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-error-rate
  namespace: monitoring
spec:
  groups:
    - name: nginx.rules
      rules:
        - alert: HighNginxErrorRate
          expr: |
            sum(rate(nginx_ingress_controller_requests{status=~"5.."}[2m]))
            /
            sum(rate(nginx_ingress_controller_requests[2m]))
            > 0.05
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "High 5xx error rate"
            description: "More than 5% of ingress requests are failing."
