apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-standard-labels
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - "*"       
      exclude:
        resources:
          namespaces:
            - monitoring
      validate:
        message: "Missing required labels: app, environment"
        pattern:
          metadata:
            labels:
              app: "?*"
              environment: "?*"
